---
- name: Install Java install JDK 11
  apt: name=openjdk-11-jdk state=present

- name: add group "tomcat"
  group: name={{tomcat_group}}

- name: add user "tomcat"
  user: name={{tomcat_user}} group={{tomcat_group}} home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo


- name: create /opt/tomcat directory
  file:
     path: /opt/tomcat
     state: directory
     mode: 0755


- name: Download Tomcat and Extract archive
  unarchive:
   src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
   dest: /opt/tomcat
   remote_src: yes
   extra_opts: [--strip-components=1]

- name: Symlink install directory
  file: src=/opt/apache-tomcat-9.0.65 path=/usr/share/tomcat state=link force=yes



- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Configure Tomcat server
  copy: src=./tomcat.service dest=/etc/systemd/system/ mode=0755


  
- name: Create  sample directory
  file: 
    path: "/opt/apache-tomcat-9.0.65/webapps/samples"
    state: directory
    mode: 0777
  become: true
  

- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/tomcat/webapps/


  notify: restart tomcat
  
- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true
  
